"""123

Revision ID: 4e1bf8679910
Revises: 32d53abdadea
Create Date: 2022-09-13 21:59:24.133165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1bf8679910'
down_revision = '32d53abdadea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picnic_registration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('picnic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['picnic_id'], ['picnic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picnic_registration')
    # ### end Alembic commands ###
